import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-chiron',
  imports: [],
  templateUrl: './chiron.component.html',
  styleUrls: ['./chiron.component.scss']
})
export class ChironComponent {
  chironMessage: string = `DATA-STREAM INITIATED "800000 RECOVERED HDDS" CRYPTO-COLLAPSE HARD TECHNO -- SUBVERTS GLOBAL SURVEILLANCE NETWORK... AES-256 "DERANGEMENT" AFFINE_TRANSFORMATION ACCESS POINT BUY-YOUR-GOLD IEE RESISTANT DISINCLINED ZERO-DAY VULNERABILITY EXPLOITS UNITED_FEDERAL_AGENCY "OVERRIDE DOWN POWER" COMPROMISED OUTSIDE GRID RECUMBANT GRID KEY-SECURED CYBERSPACE PROPERTY -ONLINE TRUST- NO-NETWORK SYNTHETIC IDENTITY DATAGRAM PROTOCOL TEXT-NOW-TO-CHAT GENERATED_FIREWALLS IEEE754-2019 CORPORATE ID DISABLED FREE-REAL-ESTATE ALGORITHM ACTIVATED CIRCUITS JAMMED VIRTUAL.INSURGENCY INFILTRATION OF THE`
}
